My_Social_Project/App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/',views.sign_up, name='signup'),
    path('login/',views.login_page, name='login'),
    path('logout/',views.logout_user, name='logout'),
    path('edit/',views.edit_profile, name='edit'),
    path('profile/',views.profile, name='profile'),
    path('user/<username>',views.user, name='user'),
    path('follow/<username>',views.follow, name='follow'),
    path('unfollow/<username>',views.unfollow, name='unfollow'),
    
]

My_Social_Project/My_Social_Project/urls.py
from django.contrib import admin
from django.urls import path,include
from App_posts import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('post/', include('App_posts.urls')),
    path('', views.home, name='home'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Social_Project/App_Login/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    profile_picture = models.ImageField(upload_to = 'profile_pics', blank=True)
    full_name = models.CharField(max_length=155, blank=True)
    dob = models.DateField(blank=True, null=True)
    website = models.URLField(blank=True)
    facebook = models.URLField(blank=True)

class Follow(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower')
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    created_date = models.DateTimeField(auto_now_add=True)
# Create your models here.

My_Social_Project/App_Login/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.db import models
from django.forms import fields
from App_Login.models import UserProfile

class CreateNewUser(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','email','password1','password2')


class EditProfile(forms.ModelForm):
    class Meta:
        model= UserProfile
        exclude=('user',)

My_Social_Project/App_Login/views.py
from django.contrib.auth.models import User
from django.shortcuts import render,HttpResponseRedirect
from django.urls import reverse
from App_Login.forms import CreateNewUser, EditProfile
from App_Login.models import UserProfile
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required

from App_Login.models import Follow


from App_posts import forms
from App_posts.models import Posts
def sign_up(request):
    form = CreateNewUser()
    registered = False
    if request.method=='POST':
        form = CreateNewUser(data=request.POST)
        if form.is_valid():
            user = form.save()
            registered = True
            user_profile = UserProfile(user=user)
            user_profile.save()
            return HttpResponseRedirect(reverse('App_Login:login'))
    return render(request, 'App_Login/signup.html', context={'form':form})


def login_page(request):
    form = AuthenticationForm()
    if request.method=='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user=authenticate(username=username, password = password)
            if user is not None:
                login(request,user)
                return HttpResponseRedirect(reverse('App_posts:home'))
                

    return render(request,'App_login/login.html', context={'form':form})


@login_required
def edit_profile(request):
    current_user = UserProfile.objects.get(user=request.user)
    form = EditProfile(instance=current_user)
    if request.method=='POST':
        form = EditProfile(request.POST, request.FILES, instance=current_user)
        if form.is_valid():
            form.save()
            form = EditProfile(instance=current_user)
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_login/profile.html', context={'form':form})


@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_Login:login'))

@login_required
def profile(request):
    
    form = forms.PostForm()
    if request.method=='POST':
        form = forms.PostForm(request.POST, request.FILES)
        if form.is_valid():
            post=form.save(commit=False)
            post.author = request.user
            post.save()
            return HttpResponseRedirect(reverse('home'))
    return render(request, 'App_Login/user.html', context={'form':form,})


@login_required
def user(request,username):
    other_user = User.objects.get(username=username)
    already_following = Follow.objects.filter(following = other_user, follower = request.user)
    if other_user==request.user:
        return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/other_user.html', context={'other_user':other_user, 'already_following':already_following})


@login_required
def follow(request, username):
    following_user = User.objects.get(username=username)
    follower_user = request.user
    already_following = Follow.objects.filter(following = following_user, follower = follower_user)
    if not already_following:
        followed_user = Follow(follower=follower_user,following=following_user)
        followed_user.save()

    return HttpResponseRedirect(reverse('App_Login:user',kwargs={'username':username}))


@login_required
def unfollow(request, username):

    unfollowing_user = User.objects.get(username=username)
    unfollower_user = request.user
    already_following = Follow.objects.filter(following = unfollowing_user, follower = unfollower_user)
    already_following.delete()

    return HttpResponseRedirect(reverse('App_Login:user', kwargs={'username':username}))

# Create your views here.

My_Social_Project/templates/App_login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<form method="POST">

    {{form|crispy}}
    {% csrf_token %}

    <input type="submit" value="Login">
</form>

{% endblock %}

My_Social_Project/templates/App_login/other_user.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="row">
    <div class="col-md-4">
        {% if other_user.user_profile.profile_picture %}
        <img src="/media/{{other_user.user_profile.profile_picture}}" alt="" height="200px" width="200px"
            style="background-color: brown;border-radius: 200px;">
        {% else %}
        <img src="/media/default.png" alt="" height="200px" width="200px"
            style="background-color: brown;border-radius: 200px;">
        {% endif %}
        
        <h2>{{other_user}}</h2>
        
        <h2>Follower {{other_user.following.count}} &nbsp &nbsp Following {{other_user.follower.count}}</h2>

        {% if not already_following %}
        <a href="{% url 'App_Login:follow' username=other_user.username %}" class="btn btn-primary">Follow</a>
        {% else %}
        <a href="{% url 'App_Login:unfollow' username=other_user.username %}" class="btn btn-primary">Unfollow</a>
        {% endif %}

    </div>
    <div class="col-md-8">
        
    {% for post in other_user.posts.all %}
        <h6>{{post.author}}</h6>
        <p>{{post.upload_data}}</p>
        {% if post.caption %}
            <p>{{post.caption}}</p>
        {% endif %}
        
        <img src="/media/{{post.image}}" height="auto" width="400px" alt="">
        <br><br>
    {% endfor %}

    </div>
</div>
{% endblock %}

My_Social_Project/templates/App_login/profile.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}

{% block content %}
<form method="POST" enctype="multipart/form-data">
    {{form|crispy}}
    {% csrf_token %}

    <input type="submit" value="Edit" class="btn btn-primary">
</form>
{% endblock %}

My_Social_Project/templates/App_login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<form method="POST">

    {{form|crispy}}
    {% csrf_token %}

    <input type="submit" value="Sign up">
</form>

<script>
    var rmv = document.querySelector('#hint_id_password1')
    rmv.remove()
</script>
{% endblock %}

My_Social_Project/templates/App_login/user.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="row">
    <div class="col-md-4">
        {% if user.user_profile.profile_picture %}
        <img src="/media/{{user.user_profile.profile_picture}}" alt="" height="200px" width="200px"
            style="background-color: brown;border-radius: 200px;">
        {% else %}
        <img src="/media/default.png" alt="" height="200px" width="200px"
            style="background-color: brown;border-radius: 200px;">
        {% endif %}
        <a href="{% url 'App_Login:edit' %}">
            <h2>{{user}}</h2>
        </a>
        <h2>Follower {{user.following.count}} &nbsp &nbsp Following {{user.follower.count}}</h2>
    </div>
    <div class="col-md-8">
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
            Add Post
        </button>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form method="POST" enctype="multipart/form-data">
                        <div class="modal-body">
                            {{form|crispy}}
                            {% csrf_token %}
                        </div>
                        <div class="modal-footer">
                            <!-- <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button> -->
                            <button type="submit" class="btn btn-primary" data-bs-dismiss="modal">Post</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- all_post -->
    
    {% for post in user.posts.all %}
        <h6>{{post.author}}</h6>
        <p>{{post.upload_data}}</p>
        {% if post.caption %}
            <p>{{post.caption}}</p>
        {% endif %}
        
        <img src="/media/{{post.image}}" height="auto" width="400px" alt="">
        <br><br>
    {% endfor %}

    </div>
</div>
{% endblock %}