My_Social_Project/App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/',views.sign_up, name='signup'),
    path('login/',views.login_page, name='login'),
    path('logout/',views.logout_user, name='logout'),
    path('edit/',views.edit_profile, name='edit'),
    path('profile/',views.profile, name='profile'),
    path('user/<username>',views.user, name='user'),
    path('follow/<username>',views.follow, name='follow'),
    path('unfollow/<username>',views.unfollow, name='unfollow'),
    
]

My_Social_Project/App_posts/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from App_posts import views


app_name = 'App_posts'

urlpatterns=[
    path('', views.home, name='home'),
    path('like/<int:id>', views.like, name='like'),
    path('unlike/<int:id>', views.unlike, name='unlike'),
]

My_Social_Project/My_Social_Project/urls.py
from django.contrib import admin
from django.urls import path,include
from App_posts import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('post/', include('App_posts.urls')),
    path('', views.home, name='home'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Social_Project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        {% block content %}
        
        {% endblock %}
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

My_Social_Project/templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'css/all.css' %}">
</head>

<body>
  <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'App_posts:home' %}">
        <img src="{% static 'images/logo.png' %}" alt="" width="50" height="auto" class="d-inline-block align-text-top">
      </a>
      <form method="GET" class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search Usermane" name="search" aria-label="Search">
        <button class="btn btn-primary btn-sm" type="submit">Search</button>
      </form>
      <!-- <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button> -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            {% if user.user_profile.profile_picture %}
            <a class="nav-link active" aria-current="page" href="{% url 'App_Login:profile' %}"><img
                src="/media/{{user.user_profile.profile_picture}}" alt="" height="40px" width="40px"
                style="background-color: brown;border-radius: 40px;"></a>
            {% else %}
            <a class="nav-link active" aria-current="page" href="{% url 'App_Login:profile' %}"><img
                src="/media/default.png" alt="" height="40px" width="40px"
                style="background-color: brown;border-radius: 40px;"></a>
            {% endif %}
          </li>
          <!-- <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'App_Login:edit' %}">Edit Profile</a>
              </li> -->

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'App_Login:logout' %}">Log out</a>
          </li>

        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}

    {% endblock %}
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
  <script src="{% static 'js/all.js' %}"></script>
  

</body>

</html>